SEED: 100 # [100, 200, 300]
DATASET: 'solubility_cherry2' # ['freesolv', 'esol', 'lipo', 'scgas', 'solubility', 'solubility_cherry']

BATCH_SIZE: 32 # [scgas: 128, others: 32, esol: 33 when scaffold splits with concat and kronecker]
MAX_EPOCHS: 300
K: 5

R_HOME: 'C:\Programming\R\R-4.4.2'