SEED: 100 # [100, 200, 300]
DATASET: 'freesolv' # ['freesolv', 'esol', 'lipo', 'scgas']

BATCH_SIZE: 32 # [scgas: 128, others: 32, esol: 33 when scaffold splits with concat and kronecker]
MAX_EPOCHS: 1
K: 5

R_HOME: 'C:\Programming\R\R-4.4.2'